### PR TITLE
Feeble attempt to discover NumPy's include path a bit more properly.

### PR DESCRIPTION
**Pull request by HannesSommer**
Addressing https://github.com/ethz-asl/numpy_eigen/issues/3.

### CODE REVIEW

**Comment by margaritaG** [comment]
I am happy to approve this, however I am not sure why the fix for `numpy_eigen` not building would live in `catkin_boost_python_buildtool` and not in `numpy_eigen`?

**Comment by HannesSommer** [comment]
The reason is that `numpy_eigen` is using this to locate its python dependencies: https://github.com/ethz-asl/numpy_eigen/blob/master/package.xml#L12. This includes in particular `numpy/numpyconfig.h`, which it didn't find in https://github.com/ethz-asl/numpy_eigen/issues/3.

**Review by margaritaG — APPROVED** [review]
This does indeed solve the `fatal error: numpy/numpyconfig.h: No such file or directory
` error from https://github.com/ethz-asl/numpy_eigen/issues/3

Amazing, thanks Hannes!

**Comment by HannesSommer** [comment]
Thanks @margaritaG for the feedback! I rebased on the change that came in since then - hopefully correctly. Merging this now.

**Pull request merged**
